server:
  port: 8090
spring:
  data:
    mongodb:
      username: cristian
      password: cristian
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin